<a href="https://colab.research.google.com/github/meshhat/SDS-CP026-retail-pulse/blob/main/retail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

# Replace 'your_file.csv' with your actual file path
df = pd.read_csv('TechCorner_Sales_update.csv')

print(df.head(2))

   Cus.ID        Date     Cus. Location  Age Gender              Mobile Name  \
0       1  27-05-2024   Rangamati Sadar   49      F      Galaxy A55 5G 8/128
1       2  27-05-2024  Inside Rangamati   44      M  Redmi Note 12 Pro 8/128

   Sell Price Does he/she Come from Facebook Page?  \
0     17073.0                                   No
1     15546.0                                  Yes

  Does he/she Followed Our Page? Did he/she buy any mobile before?  \
0                            Yes                                No
1                             No                                No

  Did he/she hear of our shop before?
0                                 Yes
1                                 Yes

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8871 entries, 0 to 8870
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Cus.ID                                8871 non-null   int64
 1   Date                                  8871 non-null   object
 2   Cus. Location                         8871 non-null   object
 3   Age                                   8871 non-null   int64
 4   Gender                                8871 non-null   object
 5   Mobile Name                           8871 non-null   object
 6   Sell Price                            8871 non-null   float64
 7   Does he/she Come from Facebook Page?  8871 non-null   object
 8   Does he/she Followed Our Page?        8871 non-null   object
 9   Did he/she buy any mobile before?     8871 non-null   object
 10  Did he/she hear of our shop before?   8871 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 762.5+ KB
None

In [8]:
df.shape

(8871, 11)

In [9]:
df.columns

Index(['Cus.ID', 'Date', 'Cus. Location', 'Age', 'Gender', 'Mobile Name',
       'Sell Price', 'Does he/she Come from Facebook Page?',
       'Does he/she Followed Our Page?', 'Did he/she buy any mobile before?',
       'Did he/she hear of our shop before?'],
      dtype='object')

In [11]:
df['Cus. Location'].value_counts()[:10]

Cus. Location
Outside Rangamati    3000
Rangamati Sadar      2972
Inside Rangamati     2899
Name: count, dtype: int64

In [12]:
df['Does he/she Come from Facebook Page?'].value_counts()[:10]

Does he/she Come from Facebook Page?
No     5781
Yes    3090
Name: count, dtype: int64